import { EventModel } from '../shared/models/event.model';

export const events: Array<EventModel> = [
    {
        name: 'Evento 1',
        description: 'The best event in the world',
        localization: {
            lat: 1,
            long: 1,
        },
        max_inscription_date: new Date('2020-10-14'),
        init_presentation_date: new Date('2020-10-14'),
        end_presentation_date: new Date('2020-10-14'),
        likes: 10,
        type: 'Social',
        pictures: ['https://images.pexels.com/photos/3755760/pexels-photo-3755760.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'],
        id: 1,
        owner: 1,
    },
    {
        name: 'Evento 1',
        description: 'The best event in the world',
        localization: {
            lat: 1,
            long: 1,
        },
        max_inscription_date: new Date('2020-10-14'),
        init_presentation_date: new Date('2020-10-14'),
        end_presentation_date: new Date('2020-10-14'),
        likes: 10,
        type: 'Social',
        pictures: ['https://images.pexels.com/photos/3755760/pexels-photo-3755760.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'],
        id: 1,
        owner: 1,
    },
    {
        name: 'Evento 1',
        description: 'The best event in the world',
        localization: {
            lat: 1,
            long: 1,
        },
        max_inscription_date: new Date('2020-10-14'),
        init_presentation_date: new Date('2020-10-14'),
        end_presentation_date: new Date('2020-10-14'),
        likes: 10,
        type: 'Social',
        pictures: ['https://images.pexels.com/photos/3755760/pexels-photo-3755760.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'],
        id: 1,
        owner: 1,
    },
    {
        name: 'Evento 1',
        description: 'The best event in the world',
        localization: {
            lat: 1,
            long: 1,
        },
        max_inscription_date: new Date('2020-10-14'),
        init_presentation_date: new Date('2020-10-14'),
        end_presentation_date: new Date('2020-10-14'),
        likes: 10,
        type: 'Social',
        pictures: ['https://images.pexels.com/photos/3755760/pexels-photo-3755760.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'],
        id: 1,
        owner: 1,
    },
    {
        name: 'Evento 1',
        description: 'The best event in the world',
        localization: {
            lat: 1,
            long: 1,
        },
        max_inscription_date: new Date('2020-10-14'),
        init_presentation_date: new Date('2020-10-14'),
        end_presentation_date: new Date('2020-10-14'),
        likes: 10,
        type: 'Social',
        pictures: ['https://images.pexels.com/photos/3755760/pexels-photo-3755760.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500'],
        id: 1,
        owner: 1,
    },
]